---
# Per environment values which override defaults in hmpps-parom-service-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: parom-service-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    NDELIUS-INTEGRATION-API_URL: "https://parom-and-delius-preprod.hmpps.service.justice.gov.uk"
    FRONTEND_URL: "https://parom-service-ui-preprod.hmpps.service.justice.gov.uk"
    SPRINGDOC_API-DOCS_ENABLED: "true"
    SPRINGDOC_SWAGGER-UI_ENABLED: "true"

  scheduledDowntime:
    enabled: true

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - moj_cloud_platform
      - delius-preprod
      - mod-platform-live

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-parom-service-notifications
